# 优惠服务   使用 nacos 配置中心文件

#server:
#  port: 7000
#
#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#  application:
#    name: gulimall-coupon
#
#
#
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto

