server:
  port: 80

# 开启降级fein.hystrix
feign:
  hystrix:
    enabled: true

# Eureka配置
eureka:
  client:
    register-with-eureka: false # 不向Eureka中注册自己
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/
